# Generated by Django 5.0.6 on 2024-07-03 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('final_products', '0001_initial'),
        ('printed_pieces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMPrintedPiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_products.finalproduct')),
                ('printed_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printed_pieces.printedpiece')),
            ],
        ),
    ]
