# Generated by Django 5.0.6 on 2024-07-05 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_printed_pieces', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('final_products', '0002_alter_finalproduct_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomprintedpiece',
            name='printed_piece',
        ),
        migrations.AddField(
            model_name='bomprintedpiece',
            name='content_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bomprintedpiece',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomprintedpiece',
            name='final_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='final_products.finalproduct'),
        ),
    ]
