# Generated by Django 5.0.6 on 2024-07-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_printed_pieces', '0002_remove_bomprintedpiece_printed_piece_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomprintedpiece',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='bomprintedpiece',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
