# Generated by Django 5.0.6 on 2024-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Approved', 'Aprobado'), ('Received', 'Recibido'), ('Closed', 'Cerrado'), ('Canceled', 'Cancelado')], default='Pending', max_length=10),
        ),
    ]
