# Generated by Django 5.0.6 on 2024-07-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchaseorderitem_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
