version: '3.8'
services:
  db:
    image: postgres:15
    container_name: erp_postgres
    environment:
      - POSTGRES_DB=erp_db
      - POSTGRES_USER=erp_user
      - POSTGRES_PASSWORD=erp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=*
      # Si prefieres, puedes pasar las credenciales aquí o en un .env
      # - DB_NAME=erp_db
      # - DB_USER=erp_user
      # - DB_PASSWORD=erp_password
      # - DB_HOST=db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: erp_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
