# Generated by Django 5.0.6 on 2024-07-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printed_pieces', '0002_alter_printedpiecematerial_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedpiece',
            name='sku',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
