# Generated by Django 5.0.6 on 2024-12-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='IP de la impresora')),
                ('access_code', models.CharField(max_length=50, verbose_name='Código de acceso')),
                ('serial_number', models.CharField(max_length=50, verbose_name='Número de serie')),
                ('printer_name', models.CharField(max_length=100, verbose_name='Nombre de la impresora')),
                ('printer_type', models.CharField(choices=[('P1P', 'P1P'), ('P1S', 'P1S'), ('A1 Mini', 'A1 Mini')], max_length=20, verbose_name='Tipo de impresora')),
            ],
        ),
    ]
