# Generated by Django 5.0.6 on 2024-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MP', 'Material Crudo'), ('PP', 'Pieza Impresa'), ('PF', 'Producto Final')], max_length=2)),
                ('code', models.PositiveIntegerField()),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
