# Generated by Django 5.0.6 on 2024-07-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='category',
            field=models.CharField(choices=[('MP', 'Material Crudo'), ('PI', 'Pieza Impresa'), ('PF', 'Producto Final')], max_length=2),
        ),
    ]
