# Generated by Django 5.0.6 on 2024-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_alter_sku_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
