# Generated by Django 5.0.6 on 2024-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('pz', 'Piezas')], max_length=2),
        ),
    ]
