# Generated by Django 5.0.6 on 2024-07-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_material_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
