# Generated by Django 5.0.6 on 2024-07-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_material_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='quantity',
        ),
    ]
